site_name: Strimzi Stretch Cluster
site_url: https://github.com/aswinayyolath/stretch-kafka-docs
theme:
  name: readthedocs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
plugins:
    - search
    - awesome-pages
